import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE ?? 'playwright');
const accounts=JSON.parse(await readFile('.local-demo-accounts.json','utf8'));
const browser=await chromium.launch({headless:true,channel:'chrome'});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try {
  const p=accounts.find(a=>a.role==='publisher');
  await page.goto('http://127.0.0.1:5173/');
  await page.getByRole('button',{name:'Вход',exact:true}).click();
  await page.getByRole('button',{name:'Паблишер',exact:true}).click();
  await page.locator('input[autocomplete=username]').fill(p.email);
  await page.locator('input[autocomplete=current-password]').fill(p.password);
  await page.getByRole('button',{name:'Войти',exact:true}).click();
  await page.locator('aside').getByRole('button',{name:'Мои площадки',exact:true}).click();
  await page.getByText('Демо: Деловой обзор',{exact:true}).waitFor();
  assert.equal(new URL(page.url()).pathname,'/publisher/platforms');
  await page.getByRole('button',{name:'Добавить площадку',exact:true}).click();
  const name=`QA outlet ${randomUUID().slice(0,8)}`;
  await page.locator('input[name=name]').fill(name);
  await page.locator('input[name=url]').fill('https://test-outlet.example.test');
  await page.locator('input[name=theme]').fill('Технологии, Бизнес');
  await page.locator('input[name=mediologyRank]').fill('17');
  await page.locator('input[name=dailyReach]').fill('25000');
  await page.getByRole('textbox',{name:'Цена: Статья',exact:true}).fill('45000');
  await page.getByRole('textbox',{name:'Цена: Новость',exact:true}).fill('19000');
  await page.locator('textarea[name=requirements]').fill('QA editorial requirements');
  const pending=page.waitForResponse(r=>r.url().endsWith('/api/outlets')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Отправить на модерацию',exact:true}).click();
  const res=await pending;assert.equal(res.status(),200,await res.text());
  const outlet=await res.json();assert.equal(outlet.prices.news,1900000);assert.equal(outlet.details.medialogiaRank,17);
  await page.getByRole('cell',{name,exact:true}).click();
  await page.getByRole('heading',{name,exact:true}).waitFor();
  await page.reload();await page.getByRole('heading',{name,exact:true}).waitFor();
  await page.getByRole('button',{name:'Редактировать',exact:true}).click();
  assert.equal(await page.locator('input[name=mediologyRank]').inputValue(),'17');
  await page.locator('input[name=name]').fill(`${name} edited`);
  await page.getByRole('button',{name:'Сохранить изменения',exact:true}).click();
  await page.getByRole('heading',{name:`${name} edited`,exact:true}).waitFor();
  await page.evaluate(()=>Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{}))));
  await page.screenshot({path:'/tmp/axioma-outlet-created.png',fullPage:true});
  const admin=accounts.find(a=>a.role==='admin');
  const adminPage=await browser.newPage();
  await adminPage.goto(`http://127.0.0.1:5173/admin/login`);
  await adminPage.locator('input[autocomplete=username]').fill(admin.email);
  await adminPage.locator('input[autocomplete=current-password]').fill(admin.password);
  await adminPage.getByRole('button',{name:'Войти',exact:true}).click();
  await adminPage.locator('aside').getByText(admin.email,{exact:true}).waitFor();
  await adminPage.goto(`http://127.0.0.1:5173/admin/platform-detail?outlet=${outlet.id}`);
  await adminPage.getByRole('button',{name:'Принять площадку',exact:true}).click();
  await adminPage.getByText('Принята',{exact:true}).waitFor();
  const customer=accounts.find(a=>a.role==='customer');
  const customerPage=await browser.newPage();
  await customerPage.goto('http://127.0.0.1:5173/customer');
  await customerPage.getByRole('button',{name:'Вход',exact:true}).click();
  await customerPage.locator('input[autocomplete=username]').fill(customer.email);
  await customerPage.locator('input[autocomplete=current-password]').fill(customer.password);
  await customerPage.getByRole('button',{name:'Войти',exact:true}).click();
  await customerPage.locator('aside').getByText(customer.email,{exact:true}).waitFor();
  assert.equal(new URL(customerPage.url()).pathname,'/customer');
  const catalogue=await customerPage.request.get('http://127.0.0.1:5173/api/outlets');
  assert.ok((await catalogue.json()).some(o=>o.id===outlet.id));
  const materials=await customerPage.request.get('http://127.0.0.1:5173/api/materials');
  assert.equal((await materials.json()).length,8);
  await customerPage.locator('aside').getByRole('button',{name:'Материалы',exact:true}).click();
  await customerPage.getByText('Демо: Новая платформа помогает компаниям планировать публикации',{exact:true}).waitFor();
  await customerPage.screenshot({path:'/tmp/axioma-demo-materials.png',fullPage:true});
  await adminPage.close();await customerPage.close();
  assert.deepEqual(errors,[]);
  console.log('Outlet create/edit/approval, customer catalogue and demo materials passed');
} catch(error) {console.error(await page.locator('body').innerText());throw error;}
finally {await browser.close();}
