import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE ?? 'playwright');
const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL || 'chrome'});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
page.setDefaultTimeout(12000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try {
  await page.goto('http://127.0.0.1:5173/');
  await page.getByRole('button',{name:'Зарегистрироваться',exact:true}).first().click();
  await page.locator('input[type=email]').fill(`prototype-${randomUUID()}@example.test`);
  await page.locator('input[autocomplete=new-password]').fill(randomUUID());
  await page.getByRole('button',{name:'Создать кабинет заказчика',exact:true}).click();
  await page.getByRole('heading',{name:'Панель заказчика',exact:true}).waitFor();
  assert.equal(await page.locator('aside').isVisible(),true);
  await page.locator('aside').getByRole('button',{name:'Проекты',exact:true}).click();
  await page.getByRole('button',{name:'Создать проект',exact:true}).click();
  await page.getByPlaceholder('Например, запуск нового продукта').fill('Project without advertiser');
  assert.equal(await page.getByRole('button',{name:'Рекламодателей пока нет',exact:true}).isDisabled(),true);
  await page.screenshot({path:'/tmp/axioma-project-empty.png',fullPage:true});
  await page.getByRole('button',{name:'Создать проект',exact:true}).last().click();
  await page.getByRole('heading',{name:'Project without advertiser',exact:true}).waitFor();
  await page.reload();
  await page.locator('aside').getByRole('button',{name:'Проекты',exact:true}).click();
  await page.getByText('Project without advertiser',{exact:true}).waitFor();
  await page.locator('aside').getByRole('button',{name:'Рекламодатели',exact:true}).click();
  await page.getByRole('button',{name:'Добавить рекламодателя',exact:true}).click();
  await page.getByPlaceholder('ООО «Название компании»').fill('QA advertiser');
  await page.getByPlaceholder('7700000000',{exact:true}).fill('7700000000');
  await page.getByPlaceholder('770001001',{exact:true}).fill('770001001');
  await page.getByPlaceholder('1237700000000',{exact:true}).fill('1237700000000');
  await page.getByPlaceholder('Индекс, город, улица, дом',{exact:true}).fill('123100, Москва, Тестовая улица, 1');
  await page.getByRole('button',{name:'Сохранить рекламодателя',exact:true}).click();
  await page.getByText('QA advertiser',{exact:true}).waitFor();
  await page.locator('aside').getByRole('button',{name:'Материалы',exact:true}).click();
  await page.getByRole('button',{name:/Загрузить материал|Добавить материал|Создать материал/}).first().click();
  await page.getByPlaceholder('Введите заголовок материала').fill('QA original interface');
  const editor=page.getByRole('textbox',{name:'Текст материала',exact:true});
  await editor.fill('Persistent prototype text');
  await editor.evaluate(node=>{const range=document.createRange();range.selectNodeContents(node);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);});
  await page.getByRole('button',{name:'Жирный',exact:true}).click();
  assert.match(await editor.innerHTML(),/<(b|strong)>Persistent prototype text<\/(b|strong)>/);
  // The only available advertiser is already selected by the original selector.
  const advertiserLabel=page.locator('label').filter({has:page.getByText('Рекламодатель',{exact:true})});
  await advertiserLabel.getByRole('button').click();
  await page.getByRole('option',{name:'QA advertiser',exact:true}).click();
  await page.locator('input[type=file][accept=".pdf,.docx,.txt"]').setInputFiles({name:'brief.txt',mimeType:'text/plain',buffer:Buffer.from('Attached original brief')});
  await page.getByText('brief.txt',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Сохранить и добавить еще материал',exact:true}).click();
  await page.getByRole('heading',{name:'Материал 2',exact:true}).waitFor();
  assert.equal(await page.getByPlaceholder('Введите заголовок материала').first().inputValue(),'QA original interface');
  await page.reload();
  await page.locator('aside').getByRole('button',{name:'Материалы',exact:true}).click();
  await page.getByText('QA original interface',{exact:true}).click();
  await page.getByText('Persistent prototype text',{exact:true}).waitFor();
  const attachment=page.getByRole('link',{name:/brief.txt/});
  await attachment.waitFor();
  const downloaded=await page.request.get(new URL(await attachment.getAttribute('href'),page.url()).href);
  assert.equal(await downloaded.text(),'Attached original brief');
  assert.equal(await page.getByText('Финтех Решения запускает новую платформу аналитики',{exact:true}).count(),0);
  await page.getByRole('button',{name:'Редактировать материал',exact:true}).click();
  assert.equal((await page.getByRole('textbox',{name:'Текст материала',exact:true}).textContent())?.trim(),'Persistent prototype text');
  assert.equal(await page.getByRole('button',{name:'Сохранить и добавить еще материал',exact:true}).count(),0);
  await page.screenshot({path:'/tmp/axioma-original-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'/tmp/axioma-original-mobile.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  assert.deepEqual(errors,[]);
  console.log('Original prototype browser check passed');
} catch(error) {
  console.error(await page.locator('body').innerText());
  await page.screenshot({path:'/tmp/axioma-original-failure.png',fullPage:true});
  throw error;
} finally {await browser.close();}
