ALTER TABLE users ADD COLUMN blocked_at timestamptz;
ALTER TABLE users ADD COLUMN account_owner_id uuid REFERENCES users(id);
ALTER TABLE users ADD COLUMN team_role text CHECK (team_role IN ('admin','content','finance','viewer'));
CREATE INDEX users_account_owner ON users(account_owner_id);

CREATE TABLE account_settings (
  user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  profile jsonb NOT NULL DEFAULT '{}',
  requisites jsonb NOT NULL DEFAULT '{}',
  requisites_status text NOT NULL DEFAULT 'draft' CHECK (requisites_status IN ('draft','pending')),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE team_invitations (
  id uuid PRIMARY KEY,
  owner_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  email text NOT NULL,
  team_role text NOT NULL CHECK (team_role IN ('admin','content','finance','viewer')),
  token_hash text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  accepted_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX team_invitations_owner ON team_invitations(owner_id,created_at DESC);
CREATE UNIQUE INDEX team_invitations_pending ON team_invitations(owner_id,email) WHERE accepted_at IS NULL AND revoked_at IS NULL;

CREATE TABLE publisher_applications (
  id uuid PRIMARY KEY,
  number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  applicant_user_id uuid REFERENCES users(id),
  data jsonb NOT NULL,
  status text NOT NULL DEFAULT 'Новая' CHECK (status IN ('Новая','На проверке','Нужны данные','Одобрена','Отклонена')),
  checks jsonb NOT NULL DEFAULT '{"resource":false,"legal":false,"representative":false,"duplicate":false}',
  decision_comment text NOT NULL DEFAULT '',
  reviewer_id uuid REFERENCES users(id),
  publisher_user_id uuid REFERENCES users(id),
  invitation_hash text UNIQUE,
  invitation_expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX publisher_applications_created ON publisher_applications(created_at DESC);
