CREATE TABLE payout_requests (
  id uuid PRIMARY KEY,
  number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  publisher_id uuid NOT NULL REFERENCES users(id),
  amount bigint NOT NULL CHECK (amount > 0),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','returned','rejected')),
  requisites jsonb NOT NULL,
  comment text NOT NULL DEFAULT '',
  reviewer_id uuid REFERENCES users(id),
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX payout_requests_publisher ON payout_requests(publisher_id,created_at DESC);
CREATE INDEX payout_requests_queue ON payout_requests(status,created_at DESC);
