CREATE TABLE balance_adjustments (
  id uuid PRIMARY KEY,
  number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  user_id uuid NOT NULL REFERENCES users(id),
  direction text NOT NULL CHECK (direction IN ('credit','debit')),
  amount bigint NOT NULL CHECK (amount > 0),
  reason text NOT NULL CHECK (length(trim(reason)) >= 10),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  created_by uuid NOT NULL REFERENCES users(id),
  reviewed_by uuid REFERENCES users(id),
  review_reason text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz
);
CREATE INDEX balance_adjustments_user ON balance_adjustments(user_id,created_at DESC);
CREATE INDEX balance_adjustments_queue ON balance_adjustments(status,created_at DESC);
