CREATE TABLE topup_invoices (
  id uuid PRIMARY KEY,
  number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  owner_id uuid NOT NULL REFERENCES users(id),
  amount bigint NOT NULL CHECK (amount > 0),
  method text NOT NULL CHECK (method IN ('transfer','card','sbp')),
  payer jsonb NOT NULL,
  seller jsonb NOT NULL,
  paid_amount bigint NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),
  refunded_amount bigint NOT NULL DEFAULT 0 CHECK (refunded_amount >= 0),
  status text NOT NULL DEFAULT 'issued' CHECK (status IN ('issued','partial','paid','overpaid','partially_refunded','refunded')),
  provider_operation_id text UNIQUE,
  payment_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX topup_invoices_owner ON topup_invoices(owner_id,created_at DESC);

CREATE TABLE topup_payments (
  id uuid PRIMARY KEY,
  provider text NOT NULL DEFAULT 'tochka',
  provider_payment_id text NOT NULL,
  invoice_id uuid REFERENCES topup_invoices(id),
  amount bigint NOT NULL CHECK (amount > 0),
  payer jsonb NOT NULL DEFAULT '{}',
  status text NOT NULL CHECK (status IN ('pending','review','credited','reversed')),
  reason text NOT NULL DEFAULT '',
  provider_data jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(provider,provider_payment_id)
);
CREATE INDEX topup_payments_review ON topup_payments(status,created_at DESC);

CREATE TABLE topup_webhook_events (
  hash text PRIMARY KEY,
  event_type text NOT NULL,
  provider_payment_id text,
  received_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE topup_account_holds (
  owner_id uuid PRIMARY KEY REFERENCES users(id),
  amount bigint NOT NULL CHECK (amount > 0),
  reason text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE topup_reversals (
  id uuid PRIMARY KEY,
  provider_payment_id text NOT NULL UNIQUE,
  invoice_id uuid NOT NULL REFERENCES topup_invoices(id),
  amount bigint NOT NULL CHECK (amount > 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE topup_sync_state (
  id boolean PRIMARY KEY DEFAULT true CHECK (id),
  last_success_at timestamptz
);
INSERT INTO topup_sync_state(id) VALUES(true);
