CREATE TABLE closing_documents (
  id uuid PRIMARY KEY,
  number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  order_id uuid NOT NULL UNIQUE REFERENCES orders(id),
  customer_id uuid NOT NULL REFERENCES users(id),
  amount bigint NOT NULL CHECK (amount > 0),
  status text NOT NULL DEFAULT 'draft' CHECK (status = 'draft'),
  snapshot jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX closing_documents_customer_created ON closing_documents(customer_id,created_at DESC);
