import React,{useEffect,useState} from 'react';
import {Download} from 'lucide-react';
import {api,uploadFile} from './api';
import {useBackend} from './prototype-backend';

const panel='overflow-hidden rounded-lg border border-[#d4e0ed] bg-white';
const field='w-full rounded-lg border border-[#476788] bg-white px-4 py-3 text-sm';
const primary='rounded-lg bg-[#006bff] px-5 py-3 text-sm font-semibold text-white disabled:opacity-50';
const money=(value:any)=>`${(Number(value)/100).toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2})} ₽`;
const today=()=>new Date().toISOString().slice(0,10);

export function AdminActs() {
 const backend=useBackend(),[acts,setActs]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[customerId,setCustomerId]=useState(''),[number,setNumber]=useState(''),[issuedOn,setIssuedOn]=useState(today()),[dateFrom,setDateFrom]=useState(''),[dateTo,setDateTo]=useState(''),[orderIds,setOrderIds]=useState<string[]>([]),[file,setFile]=useState<File|null>(null),[replaceId,setReplaceId]=useState(''),[replaceReason,setReplaceReason]=useState('');
 const refresh=async()=>{const [documents,accounts]=await Promise.all([api('/acts'),api('/admin/users')]);setActs(documents);setUsers(accounts.filter((row:any)=>row.role==='customer'&&!row.account_owner_id));};
 useEffect(()=>{refresh().catch(error=>backend.setError(error.message));},[]);
 const eligible=backend.data.orders.filter((order:any)=>order.apiStatus==='completed'&&order.customer_id===customerId&&(!dateFrom||String(order.updated_at).slice(0,10)>=dateFrom)&&(!dateTo||String(order.updated_at).slice(0,10)<=dateTo)&&!acts.some(act=>act.orders.some((item:any)=>item.id===order.id)));
 const amount=eligible.filter((order:any)=>orderIds.includes(order.id)).reduce((sum:number,order:any)=>sum+Number(order.amount)-Number(order.snapshot?.disputeResolution?.customerAmount??0),0);
 const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!file||!amount)return;const ok=await backend.perform(async()=>{const uploaded=await uploadFile(file);await api('/admin/acts','POST',{customerId,number,issuedOn,dateFrom,dateTo,orderIds,amount,fileId:uploaded.id},crypto.randomUUID());await refresh();});if(ok){setNumber('');setOrderIds([]);setFile(null);}};
 const replace=async(event:React.FormEvent)=>{event.preventDefault();if(!file||!replaceId)return;const ok=await backend.perform(async()=>{const uploaded=await uploadFile(file);await api(`/admin/acts/${replaceId}/versions`,'POST',{fileId:uploaded.id,reason:replaceReason},crypto.randomUUID());await refresh();});if(ok){setReplaceId('');setReplaceReason('');setFile(null);}};
 return <div className="space-y-6"><header><h1 className="font-display text-2xl font-bold text-[#0b3558]">Документы</h1><p className="mt-1 text-sm text-[#476788]">Окончательные акты формирует «Аксиома» в 1С. Здесь загружается подписанный PDF за период.</p></header>
  <section className={panel}><div className="border-b border-[#d4e0ed] bg-[#f8f9fb] px-6 py-4 font-semibold">Акты из 1С</div><div className="divide-y divide-[#d4e0ed]">{acts.map(act=><div key={act.id} className="flex flex-wrap items-center justify-between gap-3 px-6 py-4 text-sm"><div><div className="font-semibold">№{act.number} · {act.customer_email} · {money(act.amount)}</div><div className="mt-1 text-[#476788]">{String(act.date_from).slice(0,10)} – {String(act.date_to).slice(0,10)} · {act.orders.length} размещений · версия {act.revision}</div></div><div className="flex gap-3"><a className="inline-flex items-center gap-2 text-[#006bff]" href={`/api/acts/${act.id}/pdf`}><Download size={16}/> Скачать</a><button className="text-[#476788]" onClick={()=>{setReplaceId(act.id);setFile(null);}}>Заменить PDF</button></div></div>)}{!acts.length&&<p className="px-6 py-5 text-sm text-[#476788]">Загруженных актов пока нет.</p>}</div></section>
  {replaceId?<form className={`${panel} space-y-4 p-6`} onSubmit={replace}><h2 className="font-display text-lg font-bold">Новая версия PDF</h2><input aria-label="Подписанный PDF" type="file" accept="application/pdf" required onChange={event=>setFile(event.target.files?.[0]??null)}/><textarea className={field} required minLength={10} placeholder="Причина замены" value={replaceReason} onChange={event=>setReplaceReason(event.target.value)}/><div className="flex gap-3"><button className={primary} disabled={backend.busy||!file}>Сохранить новую версию</button><button type="button" onClick={()=>setReplaceId('')}>Отмена</button></div></form>:
  <form className={`${panel} space-y-5 p-6`} onSubmit={submit}><h2 className="font-display text-lg font-bold">Загрузить акт за период</h2><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Заказчик<select className={`${field} mt-2`} required value={customerId} onChange={event=>{setCustomerId(event.target.value);setOrderIds([]);}}><option value="">Выберите заказчика</option>{users.map(user=><option key={user.id} value={user.id}>{user.email}</option>)}</select></label><label className="text-sm">Номер акта в 1С<input className={`${field} mt-2`} required maxLength={100} value={number} onChange={event=>setNumber(event.target.value)}/></label><label className="text-sm">Начало периода<input className={`${field} mt-2`} type="date" required value={dateFrom} onChange={event=>{setDateFrom(event.target.value);setOrderIds([]);}}/></label><label className="text-sm">Конец периода<input className={`${field} mt-2`} type="date" required value={dateTo} onChange={event=>{setDateTo(event.target.value);setOrderIds([]);}}/></label><label className="text-sm">Дата акта<input className={`${field} mt-2`} type="date" required value={issuedOn} onChange={event=>setIssuedOn(event.target.value)}/></label><label className="text-sm">Подписанный PDF<input className={`${field} mt-2`} type="file" accept="application/pdf" required onChange={event=>setFile(event.target.files?.[0]??null)}/></label></div>
   <div><h3 className="text-sm font-semibold">Завершённые размещения</h3><div className="mt-2 max-h-64 overflow-y-auto divide-y divide-[#d4e0ed] border-y border-[#d4e0ed]">{eligible.map((order:any)=><label key={order.id} className="flex gap-3 px-2 py-3 text-sm"><input type="checkbox" checked={orderIds.includes(order.id)} onChange={event=>setOrderIds(ids=>event.target.checked?[...ids,order.id]:ids.filter(id=>id!==order.id))}/><span>№{order.number} · {order.material} · {money(Number(order.amount)-Number(order.snapshot?.disputeResolution?.customerAmount??0))}</span></label>)}{!eligible.length&&<p className="py-3 text-sm text-[#476788]">Нет доступных завершённых размещений за период.</p>}</div></div><div className="flex flex-wrap items-center justify-between gap-3"><span className="font-semibold">Итого к сверке: {money(amount)}</span><button className={primary} disabled={backend.busy||!file||!amount||dateFrom>dateTo}>Загрузить акт из 1С</button></div></form>}
 </div>;
}

export function AdminBankReview() {
 const backend=useBackend(),[payments,setPayments]=useState<any[]>([]),[holds,setHolds]=useState<any[]>([]),[invoices,setInvoices]=useState<any[]>([]),[invoiceIds,setInvoiceIds]=useState<Record<string,string>>({}),[reasons,setReasons]=useState<Record<string,string>>({}),[amounts,setAmounts]=useState<Record<string,string>>({});
 const refresh=async()=>{const [p,h,i]=await Promise.all([api('/admin/topups/review'),api('/admin/topups/holds'),api('/admin/topups/invoices')]);setPayments(p);setHolds(h);setInvoices(i);};
 useEffect(()=>{refresh().catch(error=>backend.setError(error.message));},[]);
 const assign=async(id:string)=>{await backend.perform(async()=>{await api(`/admin/topups/review/${id}/assign`,'POST',{invoiceId:invoiceIds[id],reason:reasons[id]});await refresh();});};
 const settle=async(ownerId:string)=>{const amount=Math.round(Number((amounts[ownerId]||'').replace(',','.'))*100);if(!amount)return;await backend.perform(async()=>{await api(`/admin/topups/holds/${ownerId}/settle`,'POST',{amount,reason:reasons[ownerId]},crypto.randomUUID());await refresh();});};
 return <div className="space-y-6"><header><h1 className="font-display text-2xl font-bold">Банковская сверка</h1><p className="mt-1 text-sm text-[#476788]">Ручное решение доступно только для платежа, подтверждённого выпиской.</p></header><section className={panel}><h2 className="border-b border-[#d4e0ed] bg-[#f8f9fb] px-6 py-4 font-semibold">Платежи на проверке</h2><div className="divide-y divide-[#d4e0ed]">{payments.map(payment=><div key={payment.id} className="grid gap-4 p-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]"><div className="text-sm"><div className="font-semibold">{money(payment.amount)} · операция {payment.provider_payment_id}</div><p className="mt-1 text-[#476788]">{payment.reason} · {payment.payer?.name||payment.payer?.inn||'Плательщик не определён'}</p></div><div className="space-y-2"><select aria-label="Счет для платежа" className={field} value={invoiceIds[payment.id]||''} onChange={event=>setInvoiceIds({...invoiceIds,[payment.id]:event.target.value})}><option value="">Выберите счет</option>{invoices.map(invoice=><option key={invoice.id} value={invoice.id}>АКС-{invoice.number} · {invoice.owner_email} · {money(invoice.amount)}</option>)}</select><input className={field} placeholder="Основание ручной сверки" minLength={10} value={reasons[payment.id]||''} onChange={event=>setReasons({...reasons,[payment.id]:event.target.value})}/><button className={primary} disabled={backend.busy||!invoiceIds[payment.id]||!reasons[payment.id]||reasons[payment.id].trim().length<10} onClick={()=>assign(payment.id)}>Назначить подтверждённый платёж</button></div></div>)}{!payments.length&&<p className="p-6 text-sm text-[#476788]">Платежей на ручной сверке нет.</p>}</div></section>
  <section className={panel}><h2 className="border-b border-[#d4e0ed] bg-[#f8f9fb] px-6 py-4 font-semibold">Задолженности после возврата</h2><div className="divide-y divide-[#d4e0ed]">{holds.map(hold=><div key={hold.owner_id} className="grid gap-4 p-6 lg:grid-cols-2"><div className="text-sm"><div className="font-semibold">{hold.email} · {money(hold.amount)}</div><p className="mt-1 text-[#476788]">Новые заказы заблокированы до погашения.</p></div><div className="space-y-2"><input className={field} inputMode="decimal" placeholder="Сумма погашения, ₽" value={amounts[hold.owner_id]||''} onChange={event=>setAmounts({...amounts,[hold.owner_id]:event.target.value})}/><input className={field} placeholder="Основание" value={reasons[hold.owner_id]||''} onChange={event=>setReasons({...reasons,[hold.owner_id]:event.target.value})}/><button className={primary} disabled={backend.busy||!amounts[hold.owner_id]||!reasons[hold.owner_id]||reasons[hold.owner_id].trim().length<10} onClick={()=>settle(hold.owner_id)}>Погасить из доступного остатка</button></div></div>)}{!holds.length&&<p className="p-6 text-sm text-[#476788]">Задолженностей нет.</p>}</div></section></div>;
}
