import React, {useState} from 'react';
import {AlertCircle,ChevronLeft,ChevronRight,ExternalLink,Eye,Globe2,Link2,LoaderCircle,MessageCircle,Newspaper,Search,Sparkles,TrendingUp} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import {ReputationSourceLink,reputationCardClass,reputationSourceDomain} from './reputation-components';

const card=reputationCardClass;
const sentiment={positive:'Позитивная',negative:'Негативная',neutral:'Нейтральная',mixed:'Смешанная',unknown:'Не определена'};
const risk={low:'Низкий',medium:'Средний',high:'Высокий',unknown:'Не определен'};
const state={ready:'Ожидает проверки',success:'Доступен',failed:'Ошибка',partial:'Частично',empty:'Без ответа',unavailable:'Не подключен'};
const statusName={queued:'Сканирование в очереди',running:'Идет сканирование',completed:'Сканирование завершено',failed:'Сканирование не удалось'};
const count=value=>new Intl.NumberFormat('ru-RU').format(value??0);
const badgeTone={high:'border-[#fecaca] bg-[#fff1f1] text-[#dc2626]',medium:'border-[#d4e0ed] bg-[#f0f3f8] text-[#0b3558]',low:'border-[#bbf7d0] bg-[#dcfce7] text-[#15803d]',unknown:'border-[#d4e0ed] bg-[#f0f3f8] text-[#476788]'};

function ResultBadge({children,tone='unknown'}) {
  return <span className={`inline-flex max-w-full items-center rounded-full border px-2.5 py-1 text-xs font-semibold leading-4 ${badgeTone[tone]??badgeTone.unknown}`}>{children}</span>;
}

function AnswerText({text,sources=[]}) {
  if(!text)return <p className="text-sm text-[#476788]">Ответ не получен.</p>;
  const linked=String(text).replace(/(^|[^\]])\[(\d+)\]/g,(match,prefix,index)=>{
    const source=sources[Number(index)-1];
    return source?.url?`${prefix}[${index}](${source.url})`:match;
  });
  return <div className="min-w-0 text-sm leading-6 text-[#0b3558] [overflow-wrap:anywhere]"><ReactMarkdown components={{
    p:({children})=><p className="mb-3 last:mb-0">{children}</p>,
    ul:({children})=><ul className="mb-3 list-disc space-y-2 pl-5">{children}</ul>,
    ol:({children})=><ol className="mb-3 list-decimal space-y-2 pl-5">{children}</ol>,
    a:({href,children})=>{
      const label=typeof children==='string'&&/^https?:\/\//i.test(children)?reputationSourceDomain(children):children;
      return <a href={href} target="_blank" rel="noreferrer" title={href} className="inline-flex max-w-full items-center gap-1 align-baseline text-[#006bff] underline underline-offset-2"><span className="min-w-0 truncate">{label}</span><ExternalLink className="h-3 w-3 shrink-0" aria-hidden="true"/></a>;
    },
  }}>{linked}</ReactMarkdown></div>;
}

function answerSourceUrls(text,sources=[]) {
  const urls=[...sources.map(source=>source.url),...String(text??'').matchAll(/\[[^\]]+\]\((https?:\/\/[^\s)]+)\)/g)].map(item=>typeof item==='string'?item:item[1]);
  return [...new Set(urls.filter(url=>{try{return ['http:','https:'].includes(new URL(url).protocol);}catch{return false;}}))];
}

export function ReputationLiveContent({scan,section,workspaceTab,setWorkspaceTab,queries,Select}) {
  const [filter,setFilter]=useState('');
  const [materialPage,setMaterialPage]=useState(1);
  const [channel,setChannel]=useState('Все каналы');
  const [engine,setEngine]=useState('Все системы');
  const [selectedUrl,setSelectedUrl]=useState(null);
  const [serpQuery,setSerpQuery]=useState('');
  const [serpEngine,setSerpEngine]=useState('Яндекс');
  const [answerEngine,setAnswerEngine]=useState('Alice AI');
  const result=scan?.result;
  const materials=result?.materials??[];
  const relevant=materials.filter(item=>item.significant===true||(result?.version<2&&item.analysis?.relevance==='relevant'&&!['aggregator','reference'].includes(item.analysis?.sourceType)));
  const negative=relevant.filter(item=>item.analysis?.sentiment==='negative');
  const topicCounts=new Map();
  for(const item of negative)for(const topic of new Set(item.analysis?.topics??[]))topicCounts.set(topic,(topicCounts.get(topic)??0)+1);
  const topicEntries=[...topicCounts].sort((a,b)=>b[1]-a[1]);
  const negativeTopics=topicEntries.length>3?[...topicEntries.slice(0,2),['Прочие',topicEntries.slice(2).reduce((sum,[,value])=>sum+value,0)]]:topicEntries;
  const topicTotal=topicEntries.reduce((sum,[,value])=>sum+value,0);
  const topicColors=['#006bff','#ef4444','#48b890'];
  let topicProgress=0;
  const topicGradient=negativeTopics.map(([,value],index)=>{const start=topicProgress;topicProgress+=value/topicTotal*100;return `${topicColors[index]} ${start}% ${topicProgress}%`;}).join(', ');
  let topicShareCount=0;
  const topicPercentages=negativeTopics.map(([,value])=>{const previous=Math.round(topicShareCount/topicTotal*100);topicShareCount+=value;return Math.round(topicShareCount/topicTotal*100)-previous;});
  const media=relevant.filter(item=>item.analysis?.sourceType==='media').length;
  const shown=relevant.filter(item=>`${item.title} ${item.domain} ${(item.analysis?.topics??[]).join(' ')}`.toLowerCase().includes(filter.toLowerCase())&&(channel==='Все каналы'||(channel==='Медиа'?item.analysis?.sourceType==='media':item.analysis?.sourceType!=='media'))&&(engine==='Все системы'||item.discoveries?.some(found=>found.engine===engine)));
  const pageCount=Math.max(1,Math.ceil(shown.length/5));
  const currentPage=Math.min(materialPage,pageCount);
  const pageItems=shown.slice((currentPage-1)*5,currentPage*5);
  const selected=pageItems.find(item=>item.url===selectedUrl)??pageItems[0];
  const topics=(result?.assessment?.topics??[]).slice(0,6);
  const searches=result?.searches??[];
  const selectedSearch=searches.find(item=>item.query===(serpQuery||queries[0])&&item.engine===serpEngine);
  const selectedTop=selectedSearch?.items?.slice(0,10)??[];
  const selectedControlled=selectedTop.filter(item=>materials.some(material=>material.url===item.url&&material.controlled)).length;
  const selectedNegative=selectedTop.filter(item=>materials.some(material=>material.url===item.url&&material.analysis?.sentiment==='negative'&&material.significant)).length;
  const negativeTop=negative.filter(item=>item.discoveries.some(found=>found.kind!=='publication'&&found.position<=10)).length;
  const wordstatRows=result?.wordstat?.queries??(result?.wordstat?.totalCount!==undefined?[{query:queries[0],totalCount:result.wordstat.totalCount}]:[]);
  const selectedWordstat=wordstatRows.find(item=>item.query===(serpQuery||queries[0]));
  const firstTop=searches[0]?.items?.slice(0,10)??[];
  const controlledTop=firstTop.filter(item=>materials.some(material=>material.url===item.url&&material.controlled)).length;
  const statusLine=(source)=>state[result?.availability?.[source]]??'Нет данных';
  const googleAnswer=result?.googleAi?.[0];
  const answers={
    'Alice AI':{text:result?.alice?.text,sources:result?.alice?.sources??[]},
    'ChatGPT':{text:result?.openaiAnswer?.text,sources:[]},
    'Google AI':{text:googleAnswer?.markdown,sources:googleAnswer?.sources??[]},
  };
  const activeAnswer=answers[answerEngine];
  const activeAnswerUrls=answerSourceUrls(activeAnswer.text,activeAnswer.sources);

  if(!scan)return <div className={`${card} p-8 text-sm text-[#476788]`}>Сканирование еще не запускалось. Данные появятся после первого снимка.</div>;
  if(!result&&['queued','running'].includes(scan.status))return <div role="status" aria-label={statusName[scan.status]} aria-live="polite" className={`${card} overflow-hidden p-6 sm:p-8`}>
    <div className="flex items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-[#e7f1ff] text-[#006bff]"><LoaderCircle className="h-5 w-5 animate-spin motion-reduce:animate-none" aria-hidden="true"/></span><span className="text-sm font-semibold text-[#0b3558]">{statusName[scan.status]}</span></div>
    <div className="mt-5 h-1.5 overflow-hidden rounded-full bg-[#e7f1ff]" aria-hidden="true"><div className="reputation-scan-progress h-full w-1/3 rounded-full bg-[#006bff]"/></div>
  </div>;
  if(!result)return <div className={`${card} p-8 text-sm text-[#476788]`}>{statusName[scan.status]??'Ожидаем данные'}{scan.status==='failed'?'. Проверьте подключения и повторите запуск.':''}</div>;

  const metric=(label,value,note,Icon=Search,tone='blue')=><div className={`${card} min-w-0 p-5`}><div className="flex items-start justify-between gap-3"><div className="min-w-0 text-sm font-medium text-[#476788]">{label}</div><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-lg ${tone==='red'?'bg-[#fff1f1] text-[#ef4444]':'bg-[#e7f1ff] text-[#006bff]'}`}><Icon className="h-4 w-4" aria-hidden="true"/></span></div><div className="mt-3 text-3xl font-semibold tabular-nums text-[#0b3558]">{value}</div><div className="mt-2 line-clamp-2 min-h-8 text-xs leading-4 text-[#476788]" title={note}>{note}</div></div>;
  const materialRow=(item)=>{
    const tone=item.analysis?.sentiment==='negative'?'high':item.analysis?.sentiment==='positive'?'low':'medium';
    const found=item.discoveries?.find(entry=>entry.kind!=='publication');
    return <button key={item.url} type="button" onClick={()=>setSelectedUrl(item.url)} className={`w-full border-b border-[#d4e0ed] p-5 text-left transition-colors hover:bg-[#f8f9fb] focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#006bff] ${selected?.url===item.url?'bg-[#f1f6ff]':'bg-white'}`}><span className="flex min-w-0 items-start justify-between gap-3"><span className="min-w-0 flex-1"><span className="line-clamp-2 text-sm font-semibold leading-5 text-[#0b3558]" title={item.title}>{item.title}</span><span className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-xs text-[#476788]"><span className="min-w-0 truncate">{item.domain}</span><span>{found?.engine??'Публикация'}</span></span></span><span className="shrink-0"><ResultBadge tone={tone}>{sentiment[item.analysis?.sentiment]??'Не определена'}</ResultBadge></span></span></button>;
  };
  return <div className="space-y-6">
    {section==='Обзор'?<>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        {metric('Поисковый интерес',wordstatRows.length?count(wordstatRows[0].totalCount):'—',wordstatRows.length?wordstatRows[0].query:statusLine('wordstat'),TrendingUp)}
        {metric('Контроль выдачи',firstTop.length?`${Math.round(controlledTop/firstTop.length*100)}%`:'—',firstTop.length?`${controlledTop} из ${firstTop.length} результатов`:'Нет выдачи',Eye)}
        {metric('Негатив в Top-10',result.availability.llm==='unavailable'?'—':`${negativeTop} URL`,result.availability.llm==='unavailable'?'Анализ недоступен':'По оцененным материалам',AlertCircle,'red')}
        {metric('Репутационный спрос','—','Нет данных',Search)}
      </div>
      <div className={`${card} overflow-hidden`}>
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#d4e0ed] px-6 py-5"><h2 className="font-display text-lg font-bold text-[#0b3558]">Общая оценка репутации</h2><ResultBadge tone={result.assessment?.risk}>{result.assessment?`${risk[result.assessment.risk]} риск`:'Нет оценки'}</ResultBadge></div>
        <div className="border-b border-[#d4e0ed] px-6 py-5"><div className="text-xs text-[#476788]">Главная тема</div><div className="mt-2 text-base font-semibold leading-7 text-[#0b3558] [overflow-wrap:anywhere]">{result.assessment?.mainTopic||'Не определена'}</div></div>
        <div className="flex items-start gap-4 p-6"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[#e7f1ff] text-[#006bff]"><Sparkles className="h-5 w-5" aria-hidden="true"/></span><div className="min-w-0"><div className="text-xs font-semibold uppercase text-[#006bff]">Вывод аналитики</div><p data-assessment className="mt-2 text-base leading-7 text-[#0b3558] [overflow-wrap:anywhere]">{result.assessment?.assessment||'Оценка появится после анализа материалов.'}</p>{result.coverage?.skipped>0&&<p className="mt-3 text-xs text-[#ef4444]">Часть найденных URL не вошла в анализ: {result.coverage.skipped}.</p>}</div></div>
        <div className="grid border-t border-[#d4e0ed] sm:grid-cols-3">{[['Главное изменение',result.assessment?.mainChange||'Нет предыдущего снимка'],['Источник риска',result.assessment?.riskSource||'Не определен'],['Следующий шаг',result.assessment?.nextStep||'Проверить источники']].map(([label,value],index)=><div key={label} className={`min-w-0 p-5 ${index<2?'border-b border-[#d4e0ed] sm:border-b-0 sm:border-r':''}`}><div className="text-xs text-[#476788]">{label}</div><div className="mt-2 text-sm font-semibold leading-6 text-[#0b3558] [overflow-wrap:anywhere]">{String(value)}</div></div>)}</div>
      </div>
      <div className="grid gap-6 xl:grid-cols-[1.35fr_0.65fr]"><div className={`${card} overflow-hidden`}><div className="border-b border-[#d4e0ed] px-6 py-5"><h2 className="font-display text-lg font-bold text-[#0b3558]">Динамика поискового интереса</h2><p className="mt-1 text-sm text-[#476788]">Сохраненные поисковые запросы · Wordstat</p></div><div className="divide-y divide-[#d4e0ed]">{queries.map(query=>{const row=wordstatRows.find(item=>item.query===query);return <div key={query} className="flex flex-wrap justify-between gap-3 px-6 py-4 text-sm"><span className="break-words text-[#0b3558]">{query}</span><strong className="tabular-nums text-[#0b3558]">{row?count(row.totalCount):'—'}</strong></div>;})}</div></div><div className={`${card} overflow-hidden`}><div className="border-b border-[#d4e0ed] px-6 py-5"><h2 className="font-display text-lg font-bold text-[#0b3558]">Каналы присутствия</h2></div><div className="grid grid-cols-2">{[['Поиск',Search,searches.length?'Доступен':'Нет данных'],['Медиа',Newspaper,result.availability.llm==='unavailable'?'—':count(media)],['Telegram',MessageCircle,'Не подключен'],['Open web',Globe2,count(relevant.length)]].map(([label,Icon,value],index)=><div key={label} className={`p-5 ${index<2?'border-b border-[#d4e0ed]':''} ${index%2===0?'border-r border-[#d4e0ed]':''}`}><div className="flex items-center justify-between gap-2 text-xs text-[#476788]">{label}<Icon className="h-4 w-4 text-[#006bff]"/></div><div className="mt-2 text-lg font-semibold text-[#0b3558]">{value}</div></div>)}</div></div></div>
      <div className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]">
        <div className={`${card} overflow-hidden`}><div className="flex flex-wrap items-start justify-between gap-3 border-b border-[#d4e0ed] px-6 py-5"><div><h2 className="font-display text-lg font-bold text-[#0b3558]">Хронология сигнала</h2><p className="mt-1 text-sm text-[#476788]">События из найденных материалов</p></div><ResultBadge tone="unknown">Без вывода о причинности</ResultBadge></div><div className="grid gap-3 p-6 sm:grid-cols-2">{relevant.slice(0,4).map(item=><a key={item.url} href={item.url} target="_blank" rel="noreferrer" title={item.url} className="min-w-0 rounded-xl border border-[#d4e0ed] bg-[#f8f9fb] p-4 hover:border-[#006bff]"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#e7f1ff] text-[#006bff]"><Newspaper className="h-4 w-4"/></span><span className="mt-3 block truncate text-xs text-[#476788]">{item.date||'Дата не указана'} · {item.domain}</span><strong className="mt-1 line-clamp-2 min-h-10 text-sm leading-5 text-[#0b3558]" title={item.title}>{item.title}</strong><span className="mt-3 block border-t border-[#d4e0ed] pt-2 text-xs text-[#476788]">{item.discoveries.slice(0,2).map(found=>found.kind==='publication'?found.engine:`${found.engine} · #${found.position}`).join(' · ')}</span></a>)}{!relevant.length&&<p className="text-sm text-[#476788]">События не определены.</p>}</div></div>
        <div className={`${card} overflow-hidden`}><div className="border-b border-[#d4e0ed] px-6 py-5"><h2 className="font-display text-lg font-bold text-[#0b3558]">Структура спроса</h2><p className="mt-1 text-sm text-[#476788]">Что именно пользователи ищут</p></div><p className="p-6 text-sm leading-6 text-[#476788]">Разбивка по интентам недоступна. Частотность сохраненных запросов показана выше.</p></div>
      </div>
      <div className="grid gap-6 xl:grid-cols-2">
        <div className={`${card} overflow-hidden`}><div className="border-b border-[#d4e0ed] px-6 py-5"><h2 className="font-display text-lg font-bold text-[#0b3558]">Ключевые тематики</h2><p className="mt-1 text-sm text-[#476788]">По значимости для репутации</p></div><div className="divide-y divide-[#d4e0ed]">{topics.length?topics.map(topic=>{const tone=topic.tone==='negative'?'high':topic.tone==='positive'?'low':'medium';return <div key={topic.name} className="flex min-w-0 items-center gap-4 px-6 py-4"><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3 text-sm"><span className="min-w-0 truncate font-medium text-[#0b3558]" title={topic.name}>{topic.name}</span><strong className="shrink-0 tabular-nums text-[#0b3558]">{topic.importance}</strong></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#e8eef5]"><div className="h-full rounded-full bg-[#006bff]" style={{width:`${topic.importance}%`}}/></div></div><ResultBadge tone={tone}>{sentiment[topic.tone]??'Не определена'}</ResultBadge></div>;}) : <p className="p-6 text-sm text-[#476788]">Темы еще не оценены.</p>}</div></div>
        <div className={`${card} overflow-hidden`}><div className="border-b border-[#d4e0ed] px-6 py-5"><h2 className="font-display text-lg font-bold text-[#0b3558]">Рекомендации</h2><p className="mt-1 text-sm text-[#476788]">Приоритетные действия на основе анализа</p></div><div className="divide-y divide-[#d4e0ed]">{result.assessment?.recommendations?.length?result.assessment.recommendations.map((item,index)=><div key={`${item.title}-${index}`} className="flex gap-4 p-5"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[#e7f1ff] text-sm font-bold text-[#006bff]">{index+1}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><div className="min-w-0 text-sm font-semibold text-[#0b3558] [overflow-wrap:anywhere]">{item.title}</div><ResultBadge tone={item.priority==='high'?'high':item.priority==='medium'?'medium':'low'}>{item.priority==='high'?'Высокий':item.priority==='medium'?'Средний':'Низкий'}</ResultBadge></div><p className="mt-1 text-xs leading-5 text-[#476788] [overflow-wrap:anywhere]">{item.text}</p></div></div>):<p className="p-6 text-sm text-[#476788]">Нет обоснованных рекомендаций.</p>}</div></div>
      </div>
    </>:<>
      <div className={`${card} overflow-hidden`}><div className="flex max-w-full flex-wrap gap-1 border-b border-[#d4e0ed] p-3">{['Материалы','Поисковая выдача','Темы','Каналы','Негатив'].map(tab=><button key={tab} type="button" onClick={()=>setWorkspaceTab(tab)} className={`shrink-0 rounded-lg px-4 py-2.5 text-sm font-semibold ${workspaceTab===tab?'bg-[#e7f1ff] text-[#006bff]':'text-[#476788] hover:bg-[#f0f3f8]'}`}>{tab}</button>)}</div>{workspaceTab==='Материалы'&&<div className="grid gap-3 p-4 lg:grid-cols-[minmax(0,1fr)_180px_180px]"><label className="relative block min-w-0"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#6f88a3]"/><input aria-label="Поиск по материалам" value={filter} onChange={event=>{setFilter(event.target.value);setMaterialPage(1);}} placeholder="Поиск по материалам, источникам и темам" className="h-11 w-full min-w-0 rounded-lg border border-[#d4e0ed] bg-white pl-10 pr-4 text-sm outline-none focus:border-[#006bff] focus:ring-2 focus:ring-[#006bff]/10"/></label><Select value={channel} options={['Все каналы','Медиа','Open web']} onChange={value=>{setChannel(value);setMaterialPage(1);}}/><Select value={engine} options={['Все системы','Яндекс','Google']} onChange={value=>{setEngine(value);setMaterialPage(1);}}/></div>}</div>
      {workspaceTab==='Материалы'&&<div className="grid min-w-0 gap-6 xl:grid-cols-[minmax(0,1.2fr)_minmax(0,0.8fr)]">
        <div className={`${card} min-w-0 self-start overflow-hidden`}>
          <div className="flex items-center justify-between gap-3 border-b border-[#d4e0ed] px-5 py-4"><div><h2 className="font-display text-base font-bold text-[#0b3558]">Найденные материалы</h2><p className="mt-1 text-xs text-[#476788]">{shown.length} значимых текстовых материалов</p></div><ResultBadge tone="medium">{shown.length}</ResultBadge></div>
          <div className="divide-y divide-[#d4e0ed]">{pageItems.length?pageItems.map(materialRow):<div className="p-8 text-sm text-[#476788]">Значимых текстовых материалов пока нет.</div>}</div>
          {pageCount>1&&<div className="flex items-center justify-between gap-3 border-t border-[#d4e0ed] bg-[#f8f9fb] px-5 py-4"><span className="text-xs text-[#476788]">{(currentPage-1)*5+1}–{Math.min(currentPage*5,shown.length)} из {shown.length}</span><span className="flex gap-2"><button type="button" aria-label="Предыдущая страница" disabled={currentPage===1} onClick={()=>setMaterialPage(page=>Math.max(1,page-1))} className="flex h-9 w-9 items-center justify-center rounded-lg border border-[#d4e0ed] bg-white text-[#476788] disabled:opacity-40"><ChevronLeft className="h-4 w-4"/></button><button type="button" aria-label="Следующая страница" disabled={currentPage===pageCount} onClick={()=>setMaterialPage(page=>Math.min(pageCount,page+1))} className="flex h-9 w-9 items-center justify-center rounded-lg border border-[#d4e0ed] bg-white text-[#476788] disabled:opacity-40"><ChevronRight className="h-4 w-4"/></button></span></div>}
        </div>
        {selected&&<div className={`${card} min-w-0 self-start overflow-hidden`}>
          <div className="border-b border-[#d4e0ed] px-5 py-4"><div className="flex flex-wrap items-center gap-2"><ResultBadge tone={selected.analysis?.risk}>{risk[selected.analysis?.risk]??'Не определен'} риск</ResultBadge><ResultBadge tone="unknown">{selected.contentStatus==='full'?'Полный текст':'Анализ сниппета'}</ResultBadge></div><h2 className="mt-4 line-clamp-3 font-display text-base font-bold leading-6 text-[#0b3558] [overflow-wrap:anywhere]" title={selected.title}>{selected.title}</h2><ReputationSourceLink url={selected.url} className="mt-3"/></div>
          <div className="divide-y divide-[#d4e0ed]">{[['Краткое содержание',selected.analysis?.summary||selected.snippet||'Нет данных'],['Ключевое утверждение',selected.analysis?.claims?.[0]||'Не определено'],['Оценка репутационного риска',selected.analysis?`${risk[selected.analysis.risk]} · уверенность ${Math.round(selected.analysis.confidence*100)}%`:'Анализ не выполнен']].map(([label,value])=><div key={label} className="p-5"><div className="text-xs font-semibold uppercase text-[#6f88a3]">{label}</div><p className="mt-2 text-sm leading-6 text-[#0b3558] [overflow-wrap:anywhere]">{String(value)}</p></div>)}</div>
        </div>}
      </div>}
      {workspaceTab==='Поисковая выдача'&&<div className="space-y-6">
        <div className={`${card} overflow-hidden`}>
          <div className="flex flex-col gap-4 border-b border-[#d4e0ed] px-6 py-5 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><h2 className="font-display text-lg font-bold text-[#0b3558]">Что видит пользователь в поиске</h2><p className="mt-1 text-sm text-[#476788]">Первые десять результатов по выбранному запросу</p></div><div className="w-full lg:w-64"><Select value={serpQuery||queries[0]} options={queries} onChange={setSerpQuery}/></div></div>
          <div className="grid border-b border-[#d4e0ed] bg-[#f8f9fb] sm:grid-cols-3">{[['Частотность',selectedWordstat?`${count(selectedWordstat.totalCount)} / месяц`:'—'],['Контроль Top-10',selectedTop.length?`${selectedControlled} результатов`:'—'],['Негатив в Top-10',selectedTop.length&&result.availability.llm!=='unavailable'?`${selectedNegative} результатов`:'—']].map(([label,value],index)=><div key={label} className={`px-6 py-4 ${index<2?'border-b border-[#d4e0ed] sm:border-b-0 sm:border-r':''}`}><div className="text-xs text-[#476788]">{label}</div><div className={`mt-1 text-sm font-semibold ${index===2&&selectedNegative?'text-[#ef4444]':'text-[#0b3558]'}`}>{value}</div></div>)}</div>
          <div role="tablist" aria-label="Поисковая система" className="flex gap-6 border-b border-[#d4e0ed] px-5">{['Яндекс','Google'].map(name=><button key={name} type="button" role="tab" aria-selected={serpEngine===name} onClick={()=>setSerpEngine(name)} className={`border-b-2 px-2 py-4 text-sm font-semibold ${serpEngine===name?'border-[#006bff] text-[#006bff]':'border-transparent text-[#476788] hover:text-[#006bff]'}`}>{name}</button>)}</div>
          <div role="tabpanel" className="divide-y divide-[#d4e0ed]">{selectedTop.length?selectedTop.map(item=>{const material=materials.find(entry=>entry.url===item.url);const reference=material?.selection==='reference'||['reference','aggregator'].includes(material?.analysis?.sourceType);const tone=material?.controlled?'low':reference?'medium':material?.analysis?.sentiment==='negative'?'high':material?.analysis?.sentiment==='positive'?'low':'medium';const label=material?.controlled?'Контролируемый':reference?'Нейтральный':material?.significant?sentiment[material.analysis?.sentiment]:'Не оценен';return <a key={item.url} href={item.url} target="_blank" rel="noreferrer" title={item.url} className="flex min-w-0 items-start gap-3 px-5 py-3.5 hover:bg-[#f8f9fb] focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#006bff]"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[#f0f3f8] text-sm font-semibold text-[#0b3558]">{item.position}</span><span className="grid min-w-0 flex-1 gap-2 md:grid-cols-[minmax(0,1fr)_150px] md:items-center"><span className="min-w-0"><span className="flex items-center gap-1.5 text-xs font-medium text-[#006bff]"><span className="truncate">{reputationSourceDomain(item.url)}</span><ExternalLink className="h-3 w-3 shrink-0" aria-hidden="true"/></span><strong className="mt-1 line-clamp-2 text-sm leading-5 text-[#0b3558]" title={item.title}>{item.title}</strong>{item.snippet&&<span className="mt-1 line-clamp-2 text-xs leading-5 text-[#476788]">{item.snippet}</span>}</span><span className="md:justify-self-end"><ResultBadge tone={tone}>{label}</ResultBadge></span></span></a>;}) : <div className="p-8 text-sm text-[#476788]">{serpEngine==='Яндекс'?statusLine('yandex'):statusLine('google')}</div>}</div>
        </div>
        <div className={`${card} overflow-hidden`}><div className="border-b border-[#d4e0ed] px-6 py-5"><h2 className="font-display text-lg font-bold text-[#0b3558]">Ответы AI-сервисов</h2><p className="mt-1 text-sm text-[#476788]">По всем сохраненным запросам</p></div><div role="tablist" aria-label="AI-сервис" className="flex gap-6 overflow-x-auto border-b border-[#d4e0ed] px-5">{Object.keys(answers).map(name=><button key={name} type="button" role="tab" aria-selected={answerEngine===name} onClick={()=>setAnswerEngine(name)} className={`shrink-0 border-b-2 px-2 py-4 text-sm font-semibold ${answerEngine===name?'border-[#006bff] text-[#006bff]':'border-transparent text-[#476788]'}`}>{name}</button>)}</div><div role="tabpanel" className="p-5 sm:p-6"><blockquote className="border-l-2 border-[#006bff] pl-4"><AnswerText text={activeAnswer.text} sources={activeAnswer.sources}/></blockquote>{activeAnswerUrls.length>0&&<div className="mt-5 border-t border-[#d4e0ed] pt-4"><div className="text-xs font-semibold uppercase text-[#6f88a3]">Источники в ответе</div><div className="mt-3 flex flex-wrap gap-2">{activeAnswerUrls.map(url=><a key={url} href={url} target="_blank" rel="noreferrer" title={url} className="inline-flex min-w-0 max-w-full items-center gap-1.5 rounded-lg border border-[#d4e0ed] bg-[#f8f9fb] px-3 py-2 text-xs font-medium text-[#0b3558] hover:text-[#006bff]"><Link2 className="h-3.5 w-3.5 shrink-0 text-[#006bff]"/><span className="truncate">{reputationSourceDomain(url)}</span></a>)}</div></div>}</div></div>
        <div className="grid gap-6 lg:grid-cols-2"><div className={`${card} p-6`}><h2 className="font-display text-lg font-bold text-[#0b3558]">Поисковый интент</h2><p className="mt-3 text-sm text-[#476788]">Нет данных.</p></div><div className={`${card} p-6`}><h2 className="font-display text-lg font-bold text-[#0b3558]">География интереса</h2><p className="mt-3 text-sm text-[#476788]">{result.parameters.region}</p></div></div>
      </div>}
      {workspaceTab==='Темы'&&<div className="grid gap-6 lg:grid-cols-2">{topics.length?topics.map((topic,index)=><div key={topic.name} className={`${card} min-w-0 p-6`}><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="text-xs font-semibold uppercase text-[#6f88a3]">Тема {index+1}</div><h2 className="mt-2 font-display text-lg font-bold leading-7 text-[#0b3558] [overflow-wrap:anywhere]">{topic.name}</h2></div><ResultBadge tone={topic.tone==='negative'?'high':topic.tone==='positive'?'low':'medium'}>{sentiment[topic.tone]??'Не определена'}</ResultBadge></div><p className="mt-4 text-sm leading-6 text-[#476788] [overflow-wrap:anywhere]">{topic.description}</p><div className="mt-5 flex items-center gap-3"><div className="h-2 flex-1 overflow-hidden rounded-full bg-[#e8eef5]"><div className="h-full rounded-full bg-[#006bff]" style={{width:`${topic.importance}%`}}/></div><strong className="text-sm tabular-nums text-[#0b3558]">{topic.importance}</strong></div></div>):<div className={`${card} p-8 text-sm text-[#476788]`}>Темы появятся после оценки материалов.</div>}</div>}
      {workspaceTab==='Каналы'&&<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Яндекс',statusLine('yandex'),Search],['Google',statusLine('google'),Globe2],['Telegram','Не подключен',MessageCircle],['Ahrefs','Не подключен',Newspaper]].map(([name,value,Icon])=><div key={name} className={`${card} min-w-0 p-5`}><div className="flex items-start justify-between gap-3"><div className="text-sm font-medium text-[#476788]">{name}</div><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-[#e7f1ff] text-[#006bff]"><Icon className="h-4 w-4"/></span></div><div className="mt-3"><ResultBadge tone={value==='Доступен'?'low':'unknown'}>{value}</ResultBadge></div></div>)}</div>}
      {workspaceTab==='Негатив'&&<div className="space-y-5">
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metric('Негативных публикаций',count(negative.length),'За выбранный период',AlertCircle,'red')}{metric('В поисковом Top-10',count(negativeTop),'Яндекс и Google',Search,'red')}{metric('С признаками сети','—','Нет данных',Globe2)}{metric('Тематики',count(topicEntries.length),'В негативных материалах',Newspaper)}</div>
        <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]">
          <section className={`${card} min-w-0 self-start overflow-hidden`}><div className="border-b border-[#d4e0ed] px-6 py-5"><h2 className="font-display text-lg font-bold text-[#0b3558]">Негативные публикации</h2><p className="mt-1 text-sm text-[#476788]">{negative.length} материалов</p></div><div className="divide-y divide-[#d4e0ed]">{negative.length?negative.map(item=><a key={item.url} href={item.url} target="_blank" rel="noreferrer" title={item.url} className="flex min-w-0 items-start justify-between gap-4 px-5 py-4 hover:bg-[#f8f9fb]"><span className="min-w-0"><strong className="line-clamp-2 text-sm leading-5 text-[#0b3558]" title={item.title}>{item.title}</strong><span className="mt-1.5 block truncate text-xs text-[#476788]">{item.domain}</span></span><ResultBadge tone="high">{risk[item.analysis?.risk]??'Не определен'} риск</ResultBadge></a>):<div className="p-8 text-sm text-[#476788]">Негативных материалов не найдено или анализ не выполнен.</div>}</div></section>
          <section className={`${card} min-w-0 self-start p-5`}><h2 className="font-display text-base font-bold text-[#0b3558]">Тематики негатива</h2><p className="mt-1 text-xs text-[#476788]">Доля тематических меток в публикациях</p><div className="mt-5 flex flex-col items-center gap-5 sm:flex-row xl:flex-col"><div className="relative h-40 w-40 shrink-0 rounded-full" style={{background:topicTotal?`conic-gradient(${topicGradient})`:'#e8eef5'}} role="img" aria-label={topicTotal?negativeTopics.map(([topic],index)=>`${topic}: ${topicPercentages[index]}%`).join(', '):'Нет данных по тематикам'}><div className="absolute inset-7 flex flex-col items-center justify-center rounded-full bg-white"><span className="text-2xl font-semibold text-[#0b3558]">{count(topicTotal)}</span><span className="mt-1 text-[11px] text-[#6f88a3]">метки</span></div></div><div className="w-full space-y-3">{negativeTopics.map(([topic],index)=><div key={topic} className="flex min-w-0 items-center gap-2 text-xs"><span className="h-2.5 w-2.5 shrink-0 rounded-full" style={{backgroundColor:topicColors[index]}}/><span className="min-w-0 flex-1 break-words text-[#476788]">{topic}</span><strong className="shrink-0 text-[#0b3558]">{topicPercentages[index]}%</strong></div>)}</div></div></section>
        </div>
      </div>}
    </>}
  </div>;
}
